service provider removes disabled services from list

diff --git a/signal.handler/service_service b/signal.handler/service_service
--- a/signal.handler/service_service
+++ b/signal.handler/service_service
@@ -49,52 +49,49 @@ service_uninstall()  {
 
 service_install()  {
 # install new service from pool
-   if [[ -f $f ]]; then
-      error "service $service already installed"
-   else
-      signal @pool pool |
-      grep "^$service " |
-      while read service stamp description; do
-         signal @pool pool cat $service > $f
-         touch -d @$stamp $f
-         export p f cmd service
-         bash <<< "$(sed -n 's/^# @INSTALL *//p' $f)"				# found @INSTALL installation code: execute 
-         facettes=$(sed -n 's/^# @FACETTE *//p' $f)				# found @FACETTE list of additional service names: symlink
-         for facette in $facettes; do 
-            ln -s ${f##*/} ${f%$service}$facette
-         done
-      done
-   fi
+   [[ -f $f ]] && error "service $service already installed"
+   found=$(signal @pool pool | grep "^$service ") || error "service $service not found on pool"
+   echo -n "installing service: $service"
+   read service stamp description <<< $found
+   signal @pool pool cat $service > $f
+   touch -d @$stamp $f
+   export p f cmd service
+   bash <<< "$(sed -n 's/^# @INSTALL *//p' $f)"				# found @INSTALL installation code: execute 
+   facettes=$(sed -n 's/^# @FACETTE *//p' $f)				# found @FACETTE list of additional service names: symlink
+   [[ -z facettes ]] || echo -n ", with facettes:"
+   for facette in $facettes; do 
+      echo -n " $facette"
+      ln -s ${f##*/} ${f%$service}$facette
+   done
+   echo
 }
 
 service_state()  {
    [[ -f $f ]] && {
-      stamp="$(stat -c%Y $f)"
       [[ -x $f ]]		     # state
-      printf '%d %-14s %-10s %d'  "$(($?^1))" "$service" "$HOSTNAME" "$stamp"  
+      printf '%d %-14s %-10s %d'  "$(($?^1))" "$service" "$HOSTNAME" "$(stat -c%Y $f)"  
       echo
    }
-   return 0
+   true
 }
 
+# @INFO doesn't show disabled services - idea is that an installed, but disabled service isn't really provided.
+#       .pretend of group @servicebroker depends on this behaviour.
 service_provider()  {
-   [[ -f $f ]] && {
-      stamp="$(stat -c%Y $f)"
-      [[ -x $f ]]		     # state
-      printf '%-10s %d %-14s %d'  "$HOSTNAME" "$(($?^1))" "$service" "$stamp"  
+   [[ -x $f ]] && {
+      printf '%-10s %-14s %d' "$HOSTNAME" "$service" "$(stat -c%Y $f)"  
       echo
    }
-   return 0
+   true
 }
 
 service_stamp()  {
    [[ -f $f ]] && {
-      stamp="$(stat -c%Y $f)"
-      [[ -x $f ]]						     # state
-      printf '%d %-14s %-10s %d'  "$stamp" "$service" "$HOSTNAME" "$(($?^1))"
+      [[ -x $f ]]		  # stamp				     # state
+      printf '%d %-14s %-10s %d'  "$(stat -c%Y $f)" "$service" "$HOSTNAME" "$(($?^1))"
       echo
    }
-   return 0
+   true
 }
 
 service_list()  {
@@ -102,16 +99,18 @@ service_list()  {
       stamp="$(stat -c%Y $f)"
       [[ -h $f ]] && {
          description="$(readlink $f)" 
-         description="-> facette of ${description#*service_}"
+         description="-> ${description#*service_} $service"
       } || {
          read description < $f
-         description="${description#\#}"
+         hash='#'		# workaround for \ vs \\ escape problem
+         description="${description#$hash}"
+         description="   ${description## }"
       }
       [[ -x $f ]]							 # state
-      printf '%-14s %d %-10s %d %s'  "$service" "$stamp" "$HOSTNAME" "$(($?^1))" "${description## }"
-      echo 
-  }
-   return 0
+      printf '%-14s %d %-10s %d %s'  "$service" "$stamp" "$HOSTNAME" "$(($?^1))" "$description"
+      echo
+   }
+   true
 }
 
 service_short()  {
